### ISSUE TITLE
It's impossible to use command line commands with " "

### ISSUE THREAD

**Issue by AndrewKraevskii** [cmgriffing/will-it-blend#2]
![image](https://github.com/cmgriffing/will-it-blend/assets/75577902/0dd56ed7-19b0-4a89-a2b4-e23668ca127d)

You can see it tries to run [`rg`, `"fun`, `run"`] which is wrong it should run [`rg`, `fun run`].

**Comment by AndrewKraevskii** [comment]
there is stackoverflow question about it. Maybe we can take parser from there 
https://stackoverflow.com/questions/34118732/parse-a-command-line-string-into-flags-and-arguments-in-golang

**Comment by cmgriffing** [comment]
I believe I have this fixed now in 0.3.2 by adding a dependency "google/shlex".
